
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CEROUNA = 15;
  public static final int DOSPT = 5;
  public static final int UNOMAS = 14;
  public static final int RCONJ = 21;
  public static final int CONCAT = 11;
  public static final int CARACTER = 16;
  public static final int LLAVEIZQ = 3;
  public static final int COMA = 10;
  public static final int LLAVEDER = 4;
  public static final int EOF = 0;
  public static final int CARESP = 19;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 17;
  public static final int USORESERVADAS = 20;
  public static final int VIRGULILLA = 9;
  public static final int CEROMAS = 13;
  public static final int LEXEMA = 18;
  public static final int ASIGNA = 8;
  public static final int PORCENTDOB = 6;
  public static final int COMILLADOB = 7;
  public static final int PTCOMA = 2;
  public static final int DISYUNC = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "LLAVEIZQ",
  "LLAVEDER",
  "DOSPT",
  "PORCENTDOB",
  "COMILLADOB",
  "ASIGNA",
  "VIRGULILLA",
  "COMA",
  "CONCAT",
  "DISYUNC",
  "CEROMAS",
  "UNOMAS",
  "CEROUNA",
  "CARACTER",
  "IDENTIFICADOR",
  "LEXEMA",
  "CARESP",
  "USORESERVADAS",
  "RCONJ"
  };
}

